In [2]:
import tensorflow as tf

/Users/huzuoliang/app/Anaconda/anaconda/envs/tensorflow/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)

In [4]:
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    print(sess.run(x))
    
writer.close()

5


In [8]:
a = tf.constant([2,3], name='a')
b = tf.constant([3,6], name='b')
x = tf.add(a,b, name = 'add')
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    sess.run(x)
writer.close()

In [9]:
a = tf.constant([2, 2], name='vector')

In [11]:
b = tf.constant([[0, 1],[2, 3]], name='b')

In [12]:
import numpy as np

In [13]:
arr = np.array(range(0,1000))

In [14]:
tf.constant(arr)

<tf.Tensor 'Const_2:0' shape=(1000,) dtype=int64>

In [16]:
print(tf, tf.int32)

<module 'tensorflow' from '/Users/huzuoliang/app/Anaconda/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/__init__.py'> <dtype: 'int32'>


In [17]:
a = tf.constant([1, 2], name='a')
tf.ones_like(a)

<tf.Tensor 'ones_like:0' shape=(2,) dtype=int32>

In [18]:
linspace = tf.linspace(10.0, 13.0, 4, name="linspace")

In [21]:
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    print(sess.run(linspace))
writer.close()

[ 10.  11.  12.  13.]


In [24]:
a = tf.random_normal([4,4], mean=0.0, stddev=1.0, dtype=tf.float32)
with tf.Session() as sess:
    print(sess.run(a))

[[ 0.19054328 -1.54403543  0.76378053  1.92285252]
 [-0.69796926  0.6634863   0.29088461 -0.58835453]
 [ 0.56903839 -0.84775507 -0.95560205  0.70424622]
 [ 0.13092682  0.15586494 -1.44285083 -0.98723137]]


In [30]:
a = tf.random_shuffle([4,5])
with tf.Session() as sess:
    print(sess.run(a))

[5 4]


In [39]:
a = tf.constant([3, 6],dtype=tf.float32)
b = tf.constant([2, 2],dtype=tf.float32)

In [41]:
x = tf.matmul(tf.reshape(a,shape=[1,2]), tf.reshape(b,shape=[2,1]))
y = tf.div(a,b)
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y))

[[ 18.]]
[ 1.5  3. ]


In [45]:
t_1 = [b"apple", b"peach", b"grape"]
print(t_1.shape)

AttributeError: 'list' object has no attribute 'shape'

In [43]:
t_1 = ["apple", "peach", "grape"]
print(t_1)

['apple', 'peach', 'grape']


In [3]:
my_const = tf.constant([1,2], name='my_const')
print(tf.get_default_graph().as_graph_def())

node {
  name: "my_const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\001\000\000\000\002\000\000\000"
      }
    }
  }
}
versions {
  producer: 24
}



In [13]:
a = tf.Variable(2,name='v1')
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(a.eval())

2


In [23]:
b = a.assign(4)

In [24]:
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(b)
    print(a.eval())

4


In [28]:
sess = tf.InteractiveSession()
a = tf.constant(1)
b = tf.constant(2)

print(c.eval())
print(d.eval())
with tf.control_dependencies([a,b]):
    c = tf.multiply(a ,b)
    d = a * b
sess.close()

2
2


In [30]:
a = tf.placeholder(tf.float32,shape=[3])
b = tf.constant([1,2,3],tf.float32)
c = a+b
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./my_graph', sess.graph)
    print(sess.run(c,{a:[1,2,3]}))
writer.close()

[ 2.  4.  6.]


In [37]:
x = tf.Variable(10, name='x') 
y = tf.Variable(20, name='y')

with tf.Session() as sess:
    writer = tf.summary.FileWriter('./my_graph', sess.graph)
    sess.run(tf.global_variables_initializer()) 
    for _ in range(10):
        
        print(sess.run(tf.add(x, y))) # create the op add only when you need to compute it writer.close()
writer.close()

30
30
30
30
30
30
30
30
30
30


In [36]:
print(tf.get_default_graph().as_graph_def())

node {
  name: "my_const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\001\000\000\000\002\000\000\000"
      }
    }
  }
}
node {
  name: "v1/initial_value"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "v1"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "v1/Assign"
  op: "Assign"
  input: "v1"
  input: "v1/initial_v